### ISSUE TITLE
Remove and replace borosilicate glass

### ISSUE THREAD

**Issue by aaronreichmenberliner** [machinabio/crucible#11]
Need to remove and replace the borosilicate glass.

Try cleaning first. Order new stock.

**Comment by aaronreichmenberliner** [comment]
Ordered from McMaster Carr: https://www.mcmaster.com/#catalog/123/3690/=1851rrc

Borosilicate Glass Disc, 1-3/4" Diameter

**Comment by aaronreichmenberliner** [comment]
Wrong borosilicate glass diameter. Should be Borosilicate Glass Disc, 1-1/2" Diameter 1/8'' thick

**Comment by aaronreichmenberliner** [comment]
Done. 
![img_0290](https://user-images.githubusercontent.com/13181795/27345555-fcbf2fd2-559e-11e7-9fdb-ce53f72f5b05.JPG)

Sealant was applied to the rim of the borosilicate glass and the rim of the chamber. Care was taken to not allow the sealant to push into the visible section of the glass.

**Comment by miamirkovic** [comment]
Cleaned borosilicate with ethanol and soft cotton (test-tube brush will scratch glass). Applied thin layer of sealant to borosilicate with cotton swab and single circle of sealant to chamber rim 2cm from opening with nozzle to ensure sealant would not leak into chamber opening. @aaronreichmenberliner
