### ISSUE TITLE
seal chamber floor at ribbon cable

### ISSUE THREAD

**Issue by aaronreichmenberliner** [machinabio/crucible#18]
Seal chamber floor with sealant at ribbon cable intersection.
![img_0295](https://user-images.githubusercontent.com/13181795/27345534-e4487670-559e-11e7-885e-2660a7df75a9.JPG)

**Comment by miamirkovic** [comment]
Applied two layers of sealant around cable using nozzle and toothpick. Gently pulled cable to ensure seal. Allowed to harden. @aaronreichmenberliner

**Comment by aaronreichmenberliner** [comment]
Done.
