### ISSUE TITLE
Apply and seal screw coolant inserts into chamber floor

### ISSUE THREAD

**Issue by aaronreichmenberliner** [machinabio/crucible#19]
![img_0291](https://user-images.githubusercontent.com/13181795/27345655-5f10dbcc-559f-11e7-8065-b81530e01c06.JPG)
![img_0292](https://user-images.githubusercontent.com/13181795/27345656-5f14557c-559f-11e7-89f7-c724f9638bfc.JPG)

**Comment by miamirkovic** [comment]
Slowly heated screw coolant inserts with smaller heat exchanger and soldering iron at 450°C. Gently pressed inserts into plastic with wrench and clamped heated plastic around inserts to control plastic expansion. Allowed to cool, removed heat exchanger, and sealed with aquarium sealant using nozzle and Q-Tips. Removed excess plastic with tweezer and pliers. (In the future try removing heat exchanger while still hot and removing excess plastic before it cools) @aaronreichmenberliner
