### ISSUE TITLE
Apply and seal vacuum adaptor at intersection with manifold

### ISSUE THREAD

**Issue by aaronreichmenberliner** [machinabio/crucible#20]

**Comment by aaronreichmenberliner** [comment]
![img_0293](https://user-images.githubusercontent.com/13181795/27345753-9c7b445c-559f-11e7-915a-1f4d62e9187d.JPG)

**Comment by miamirkovic** [comment]
Applied sealant to socket within Crucible and to interior rim of adaptor using nozzle and Q-Tips. Fed tubing through adaptor and socket and secured adaptor with screws. Allowed to harden.
