### ISSUE TITLE
Document fitting specifications for all connections.

### ISSUE THREAD

**Issue by miamirkovic** [machinabio/crucible#27]
**Full Replacement Set**
Thermolator Connections
- [T-M 1/2"-1/4"](https://www.mcmaster.com/#5929k25/=189ndl8)

- [Sleeve](https://www.mcmaster.com/#52245k587/=1896ur0)

Crucible Lower Body
- [T-T 1/2"-3/8"](https://www.mcmaster.com/#5929k236/=189nlle)

Crucible Upper Body
- [T-M 1/2"-1/4"](https://www.mcmaster.com/#5929k25/=189ndl8)

- [F-M 1/4"-1/8"](https://www.mcmaster.com/#9171k62/=189n65s)

Crucible Chamber Floor
- [90° T-M 3/8"-1/8"](https://www.mcmaster.com/#5929k81/=189ndun)

**OLD AND CURRENT**
_DO NOT use these specs to replace. Use only links from replacement set above to replace_
![file_000](https://user-images.githubusercontent.com/22893461/27608078-f56b6d26-5b3a-11e7-9d9c-eb927ae70044.jpeg)

**Thermolator Connections**
Tube-M reducer (old): 1/2" to 1/4" nominal. 16 TPI. [Non-"precision" sleeve](https://www.mcmaster.com/#52245k587/=1896ur0)
Proposed replacement:
https://www.mcmaster.com/#5929k25/=189ndl8

**Crucible Lower Body Connections**
[Tube-Tube reducer:](https://www.mcmaster.com/#8239k258/=1896vy9) 1/2" to 3/8" nominal. 20 TPI. ["Precision" sleeve](https://www.mcmaster.com/#8239k227/=1896wvi) 
Proposed replacement:  https://www.mcmaster.com/#catalog/123/189/=189ng33

**Crucible Upper Body Connections**
![file_000 2](https://user-images.githubusercontent.com/22893461/27647481-6294b704-5be0-11e7-8326-c602c27a136a.jpeg)
Tube-M reducer:  1/2" to 1/4" nominal. 16 TPI. Non-"precision" sleeve. 
https://www.mcmaster.com/#5929k25/=189ndl8
F-M reducer: 1/4" to 1/8" nominal. 20 TPI to 27 TPI. https://www.mcmaster.com/#9171k62/=189n65s
Brass rings: 1/8" nominal. 27 TPI.

**Crucible Chamber Floor Connections**
![file_000 1](https://user-images.githubusercontent.com/22893461/27647775-413dc662-5be1-11e7-92d9-fe61872fda67.jpeg)
[90° Tube-M Adapter](https://www.mcmaster.com/#5929k81/=189ndun): 3/8" to 1/8", 20 TPI to 27 TPI

Brass rings: 1/8" nominal. 27 TPI.

**Comment by aaronreichmenberliner** [comment]
Nice.
