### ISSUE TITLE
Order new matched set of fittings and soldering iron tips

### ISSUE THREAD

**Issue by miamirkovic** [machinabio/crucible#28]
[Link to PDF](https://drive.google.com/open?id=0BwPHFn7Ra1-OaktSTVF4Q0lGQVU)

![](http://i.imgur.com/ucsR5YT.jpg)
![](http://i.imgur.com/93BLzDB.jpg)

**Comment by miamirkovic** [comment]
I'm on mobile, will fix labels and close when I get my computer from the lab

**Comment by aaronreichmenberliner** [comment]
aha ok. enjoy class.

———————————————
Aaron J. Berliner
Visiting Research Scientist
University of California, Berkeley
Cell: (413)-854-1692

**Comment by miamirkovic** [comment]
Got it. Desktop site is way better than any available app
