### ISSUE TITLE
Fluid perfusion through walls of chamber

### ISSUE THREAD

**Issue by miamirkovic** [machinabio/crucible#30]
Coolant system walls leak. 
Notable leaks:
![file_000 4](https://user-images.githubusercontent.com/22893461/27875227-50878578-6167-11e7-8ff5-406fdec5831a.jpeg)
![file_000 3](https://user-images.githubusercontent.com/22893461/27875237-54fb04f4-6167-11e7-84ce-9e7d86d96eb0.jpeg)

Possible solutions: 
 - [Seal via epoxy infiltration](http://www.stratasys.com/solutions/finishing-processes/sealing-fdm-parts)
 - test perfusion and off-gassing on test prints of various different materials and geometries
 - ![file_000 5](https://user-images.githubusercontent.com/22893461/27875516-45bc0172-6168-11e7-921b-ce963bd69f26.jpeg)
 - reprint coolant system piece

**Comment by aaronreichmenberliner** [comment]
Will solve using #32
