### ISSUE TITLE
Remove, repair, and clean manifold

### ISSUE THREAD

**Issue by aaronreichmenberliner** [machinabio/crucible#9]
Need to remove, repair, and clean manifold following chemical dissolution of aquarium sealant.

Need to make sure

[] aquarium sealant is removed from manifold internals

**Comment by aaronreichmenberliner** [comment]
Tested with thumbs-in pressure test. Pressure read of -95kPa

**Comment by miamirkovic** [comment]
Removed valves and grommet fasteners from manifold. Removed remaining semi-dissolved aquarium sealant from manifold with tweezers and cotton swabs. Large piece was found between two central valves. Reassembled fasteners and valves and secured with screws to manifold. Secured manifold and main circuit board with screws to Crucible and booted up. @aaronreichmenberliner
